name:                contract
version:             0.1.0.0
github:              "EugineKosenko/haskell-contract"
license:             BSD3
author:              "Eugine V. Kosenko"
maintainer:          "eugine.kosenko@gmail.com"
copyright:           "2022 Eugine V. Kosenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-contract#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell >= 2.16
- general >= 0.1
  
library:
  source-dirs: src
